import { University, ProductListing } from "./types";

export const PAKISTANI_UNIVERSITIES: University[] = [
  {
    id: "nust",
    name: "National University of Sciences & Technology",
    shortName: "NUST",
    city: "Islamabad / Rawalpindi",
    province: "Federal Capital",
    campuses: ["H-12 Islamabad (SEECS / SMME)", "CEME Rawalpindi", "CAE Risalpur"],
    programs: ["Electrical Engineering", "Computer Engineering", "Mechatronics Engineering", "Mechanical", "Robotics & AI"],
    logoBgColor: "bg-blue-900",
  },
  {
    id: "fast",
    name: "FAST National University of Computer & Emerging Sciences",
    shortName: "FAST-NUCES",
    city: "Islamabad / Lahore / Karachi / Peshawar / CFD",
    province: "National",
    campuses: ["Islamabad (H-11)", "Lahore (Faisal Town)", "Karachi (Shah Latif)", "Peshawar", "Chiniot-Faisalabad"],
    programs: ["Computer Engineering", "Electrical Engineering", "Robotics", "IoT & Embedded Systems"],
    logoBgColor: "bg-indigo-950",
  },
  {
    id: "uet-lahore",
    name: "University of Engineering & Technology, Lahore",
    shortName: "UET Lahore",
    city: "Lahore",
    province: "Punjab",
    campuses: ["Main Campus (GT Road)", "KSK Campus", "Faisalabad Campus", "Narowal Campus"],
    programs: ["Electrical Engineering", "Mechatronics & Control Engineering", "Computer Systems Engineering"],
    logoBgColor: "bg-amber-900",
  },
  {
    id: "uet-taxila",
    name: "University of Engineering & Technology, Taxila",
    shortName: "UET Taxila",
    city: "Taxila / Rawalpindi",
    province: "Punjab",
    campuses: ["Main Campus Taxila", "Chakwal Campus"],
    programs: ["Electrical Engineering", "Telecommunication Engineering", "Electronic Engineering", "Mechanical Engineering"],
    logoBgColor: "bg-emerald-950",
  },
  {
    id: "giki",
    name: "Ghulam Ishaq Khan Institute of Engineering Sciences & Technology",
    shortName: "GIKI",
    city: "Topi, Swabi",
    province: "KPK",
    campuses: ["Topi Main Campus"],
    programs: ["Electrical & Electronics Engineering", "Computer Engineering", "Materials & Robotics"],
    logoBgColor: "bg-cyan-950",
  },
  {
    id: "ned",
    name: "NED University of Engineering & Technology",
    shortName: "NED UET",
    city: "Karachi",
    province: "Sindh",
    campuses: ["Main Campus (University Road)", "LEJ Campus", "City Campus"],
    programs: ["Electronic Engineering", "Computer & Information Systems", "Electrical Engineering", "Automotive & Mechatronics"],
    logoBgColor: "bg-red-950",
  },
  {
    id: "comsats",
    name: "COMSATS University Islamabad",
    shortName: "COMSATS",
    city: "Islamabad / Lahore / Abbottabad / Wah / Attock / Sahiwal / Vehari",
    province: "Federal / Punjab / KPK",
    campuses: ["Islamabad (Park Road)", "Lahore (Defence Road)", "Wah Cantt", "Abbottabad", "Attock"],
    programs: ["Electrical & Computer Engineering", "Telecommunications", "Software Engineering"],
    logoBgColor: "bg-sky-950",
  },
  {
    id: "pieas",
    name: "Pakistan Institute of Engineering & Applied Sciences",
    shortName: "PIEAS",
    city: "Nilore, Islamabad",
    province: "Federal Capital",
    campuses: ["Nilore Main Campus"],
    programs: ["Electrical Engineering", "Mechanical Engineering", "Nuclear & Control Engineering"],
    logoBgColor: "bg-teal-950",
  },
  {
    id: "air-university",
    name: "Air University",
    shortName: "Air University",
    city: "Islamabad / Multan / Kamra",
    province: "Federal Capital",
    campuses: ["Main Campus (E-9 Islamabad)", "Aerospace Campus Kamra", "Multan Campus"],
    programs: ["Mechatronics Engineering", "Electrical Engineering", "Biomedical Engineering"],
    logoBgColor: "bg-slate-900",
  },
  {
    id: "ist",
    name: "Institute of Space Technology",
    shortName: "IST",
    city: "Islamabad (DHA Phase II)",
    province: "Federal Capital",
    campuses: ["Islamabad Highway Campus"],
    programs: ["Electrical Engineering", "Avionics Engineering", "Aerospace Engineering", "Mechanical Engineering"],
    logoBgColor: "bg-violet-950",
  },
  {
    id: "itu",
    name: "Information Technology University",
    shortName: "ITU",
    city: "Lahore",
    province: "Punjab",
    campuses: ["Arfa Software Technology Park, Ferozepur Road"],
    programs: ["Electrical Engineering", "Computer Engineering", "Robotics & Intelligent Systems"],
    logoBgColor: "bg-purple-950",
  },
  {
    id: "muet",
    name: "Mehran University of Engineering & Technology",
    shortName: "MUET",
    city: "Jamshoro",
    province: "Sindh",
    campuses: ["Jamshoro Main Campus", "Khairpur Mirs Campus"],
    programs: ["Electrical Engineering", "Electronic Engineering", "Mechatronics Engineering"],
    logoBgColor: "bg-orange-950",
  },
  {
    id: "buitems",
    name: "Balochistan University of Information Technology, Engineering and Management Sciences",
    shortName: "BUITEMS",
    city: "Quetta",
    province: "Balochistan",
    campuses: ["Takatu Campus (Airport Road)", "City Campus"],
    programs: ["Electronic Engineering", "Computer Engineering", "Telecom Engineering"],
    logoBgColor: "bg-yellow-950",
  },
  {
    id: "bahria-e8",
    name: "Bahria University (E-8 Campus)",
    shortName: "Bahria E-8",
    city: "Islamabad",
    province: "Federal Capital",
    campuses: ["E-8 Naval Complex, Islamabad"],
    programs: ["Electrical Engineering", "Software Engineering", "Computer Science", "Robotics & AI"],
    logoBgColor: "bg-blue-950",
  },
  {
    id: "bseas-h11",
    name: "Bahria School of Engineering & Applied Sciences (BSEAS H-11)",
    shortName: "BSEAS H-11",
    city: "Islamabad",
    province: "Federal Capital",
    campuses: ["H-11/4 Islamabad Campus"],
    programs: ["Electrical Engineering", "Computer Engineering", "IoT & Embedded Systems", "Data Science"],
    logoBgColor: "bg-indigo-900",
  },
  {
    id: "iiui",
    name: "International Islamic University, Islamabad (IIUI)",
    shortName: "IIUI",
    city: "Islamabad",
    province: "Federal Capital",
    campuses: ["H-10 Islamabad New Campus", "Faisal Mosque Campus"],
    programs: ["Electrical Engineering", "Mechanical Engineering", "Computer Science", "Software Engineering"],
    logoBgColor: "bg-emerald-900",
  },
  {
    id: "riphah",
    name: "Riphah International University",
    shortName: "Riphah",
    city: "Islamabad / Rawalpindi / Lahore",
    province: "Federal / Punjab",
    campuses: ["I-14 Islamabad Campus", "Al-Mizan Rawalpindi", "ETB Rawalpindi", "Raiwind Road Lahore"],
    programs: ["Electrical Engineering", "Biomedical Engineering", "Computing & AI"],
    logoBgColor: "bg-cyan-900",
  },
  {
    id: "superior",
    name: "Superior University",
    shortName: "Superior",
    city: "Lahore",
    province: "Punjab",
    campuses: ["Main Gold Campus (Raiwind Road)", "City Campus Lahore"],
    programs: ["Electrical Engineering", "Computer Science", "Robotics", "Software Engineering"],
    logoBgColor: "bg-rose-950",
  },
  {
    id: "uol",
    name: "University of Lahore (UOL)",
    shortName: "UOL",
    city: "Lahore / Islamabad",
    province: "Punjab",
    campuses: ["Defence Road Main Campus Lahore", "Islamabad Campus"],
    programs: ["Electrical Engineering", "Mechanical Engineering", "Computer Science", "Electronics"],
    logoBgColor: "bg-green-950",
  },
  {
    id: "nutech",
    name: "National University of Technology (NUTECH)",
    shortName: "NUTECH",
    city: "Islamabad",
    province: "Federal Capital",
    campuses: ["I-12 Islamabad Main Campus"],
    programs: ["Computer Engineering", "Electrical Engineering", "Mechanical Engineering"],
    logoBgColor: "bg-teal-900",
  },
  {
    id: "other",
    name: "Other (Custom / Unlisted)",
    shortName: "Other",
    city: "Pakistan",
    province: "National",
    campuses: ["Campus Hub"],
    programs: ["Engineering & Computing"],
    logoBgColor: "bg-neutral-800",
  },
];

// Pure database placeholder array (empty by default, loaded dynamically from SQLite)
export const MOCK_PRODUCTS: ProductListing[] = [];
