import { ProductListing, University, ServiceRequest } from "./types";

export const PAKISTANI_UNIVERSITIES: University[] = [
  {
    id: "nust",
    name: "National University of Sciences & Technology",
    shortName: "NUST",
    city: "Islamabad / Rawalpindi",
    province: "Federal Capital",
    campuses: ["H-12 Islamabad (SEECS / SMME)", "CEME Rawalpindi", "CAE Risalpur"],
    programs: ["Electrical Engineering", "Computer Engineering", "Mechatronics Engineering", "Mechanical", "Robotics & AI"],
    logoBgColor: "bg-blue-900",
  },
  {
    id: "fast",
    name: "FAST National University of Computer & Emerging Sciences",
    shortName: "FAST-NUCES",
    city: "Islamabad / Lahore / Karachi / Peshawar / CFD",
    province: "National",
    campuses: ["Islamabad (H-11)", "Lahore (Faisal Town)", "Karachi (Shah Latif)", "Peshawar", "Chiniot-Faisalabad"],
    programs: ["Computer Engineering", "Electrical Engineering", "Robotics", "IoT & Embedded Systems"],
    logoBgColor: "bg-indigo-950",
  },
  {
    id: "uet-lahore",
    name: "University of Engineering & Technology, Lahore",
    shortName: "UET Lahore",
    city: "Lahore",
    province: "Punjab",
    campuses: ["Main Campus (GT Road)", "KSK Campus", "Faisalabad Campus", "Narowal Campus"],
    programs: ["Electrical Engineering", "Mechatronics & Control Engineering", "Computer Systems Engineering"],
    logoBgColor: "bg-amber-900",
  },
  {
    id: "uet-taxila",
    name: "University of Engineering & Technology, Taxila",
    shortName: "UET Taxila",
    city: "Taxila / Rawalpindi",
    province: "Punjab",
    campuses: ["Main Campus Taxila", "Chakwal Campus"],
    programs: ["Electrical Engineering", "Telecommunication Engineering", "Electronic Engineering", "Mechanical Engineering"],
    logoBgColor: "bg-emerald-950",
  },
  {
    id: "giki",
    name: "Ghulam Ishaq Khan Institute of Engineering Sciences & Technology",
    shortName: "GIKI",
    city: "Topi, Swabi",
    province: "KPK",
    campuses: ["Topi Main Campus"],
    programs: ["Electrical & Electronics Engineering", "Computer Engineering", "Materials & Robotics"],
    logoBgColor: "bg-cyan-950",
  },
  {
    id: "ned",
    name: "NED University of Engineering & Technology",
    shortName: "NED UET",
    city: "Karachi",
    province: "Sindh",
    campuses: ["Main Campus (University Road)", "LEJ Campus", "City Campus"],
    programs: ["Electrical Engineering", "Electronic Engineering", "Computer & Information Systems", "Mechatronics"],
    logoBgColor: "bg-blue-950",
  },
  {
    id: "comsats",
    name: "COMSATS University Islamabad",
    shortName: "CUI",
    city: "Islamabad / Lahore / Abbottabad / Wah",
    province: "Federal / Punjab / KPK",
    campuses: ["Islamabad (Park Road)", "Lahore", "Abbottabad", "Wah Cantt", "Attock", "Sahiwal", "Vehari"],
    programs: ["Electrical & Computer Engineering", "Telecommunications", "Embedded Systems"],
    logoBgColor: "bg-sky-950",
  },
  {
    id: "pieas",
    name: "Pakistan Institute of Engineering & Applied Sciences",
    shortName: "PIEAS",
    city: "Islamabad",
    province: "Federal Capital",
    campuses: ["Nilore Campus"],
    programs: ["Electrical Engineering", "Systems & Control", "Nuclear Engineering"],
    logoBgColor: "bg-green-950",
  },
  {
    id: "air-uni",
    name: "Air University",
    shortName: "AU",
    city: "Islamabad / Multan / Kamra",
    province: "Federal / Punjab",
    campuses: ["Sector E-9 Islamabad", "Aviation Campus Kamra", "Multan Campus"],
    programs: ["Mechatronics Engineering", "Electrical Engineering", "Avionics Engineering", "Aerospace"],
    logoBgColor: "bg-blue-900",
  },
  {
    id: "ist",
    name: "Institute of Space Technology",
    shortName: "IST",
    city: "Islamabad",
    province: "Federal Capital",
    campuses: ["Islamabad Highway Campus"],
    programs: ["Electrical Engineering", "Avionics Engineering", "Materials Science & Space Tech"],
    logoBgColor: "bg-slate-900",
  },
  {
    id: "habib",
    name: "Habib University",
    shortName: "Habib",
    city: "Karachi",
    province: "Sindh",
    campuses: ["Gulistan-e-Jauhar Karachi"],
    programs: ["Electrical Engineering", "Computer Engineering"],
    logoBgColor: "bg-purple-950",
  },
  {
    id: "itu",
    name: "Information Technology University",
    shortName: "ITU Lahore",
    city: "Lahore",
    province: "Punjab",
    campuses: ["Arfa Software Technology Park", "Barki Road Campus"],
    programs: ["Electrical Engineering", "Embedded Robotics", "AI & Hardware Systems"],
    logoBgColor: "bg-teal-950",
  },
  {
    id: "uet-peshawar",
    name: "University of Engineering & Technology, Peshawar",
    shortName: "UET Peshawar",
    city: "Peshawar",
    province: "KPK",
    campuses: ["Main Campus Peshawar", "Jalozai", "Mardan", "Abbottabad", "Kohat"],
    programs: ["Mechatronics Engineering", "Electrical Engineering", "Electronic Engineering"],
    logoBgColor: "bg-red-950",
  },
  {
    id: "muet",
    name: "Mehran University of Engineering & Technology",
    shortName: "MUET",
    city: "Jamshoro",
    province: "Sindh",
    campuses: ["Main Campus Jamshoro", "Khairpur Mirs Campus"],
    programs: ["Electrical Engineering", "Mechatronics Engineering", "Electronic Engineering", "Telecommunication"],
    logoBgColor: "bg-emerald-900",
  },
  {
    id: "buitems",
    name: "Balochistan University of Information Technology, Engineering & Management Sciences",
    shortName: "BUITEMS",
    city: "Quetta",
    province: "Balochistan",
    campuses: ["Takatu Campus", "City Campus"],
    programs: ["Electronic Engineering", "Telecommunication Engineering", "Computer Engineering"],
    logoBgColor: "bg-blue-950",
  },
];

export const MOCK_PRODUCTS: ProductListing[] = [
  {
    id: "tech-001",
    title: "Raspberry Pi 4 Model B (4GB RAM) + Aluminum Armor Heat Sink Case",
    category: "development_boards",
    condition: "fyp_tested",
    pricePkr: 14500,
    originalPricePkr: 22000,
    isNegotiable: true,
    images: [
      "https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Used for 3 months in our AI Computer Vision FYP. 100% working condition, thoroughly stress-tested with dual display and camera interface. Includes dual fan passive/active aluminum armor heatsink case and 5V 3A Type-C power adapter.",
    specs: {
      "RAM": "4GB LPDDR4-3200",
      "Processor": "Broadcom BCM2711, Quad-core Cortex-A72 @ 1.5GHz",
      "Condition": "Pristine, 0 overheating issues",
      "Includes": "Heatsink Case, 32GB SanDisk Ultra SD Card",
    },
    seller: {
      id: "u-101",
      name: "Hamza Tariq",
      university: "NUST (SEECS)",
      campus: "Sector H-12, Islamabad",
      city: "Islamabad",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 4.9,
      phone: "+923005551234",
    },
    quantityAvailable: 1,
    status: "available",
    createdAt: "2026-08-30T10:00:00Z",
    viewsCount: 148,
    location: "NUST H-12 Campus / Rawalpindi",
  },
  {
    id: "tech-002",
    title: "ESP32-CAM WiFi + Bluetooth Camera Module with OV2640 2MP + FTDI Programmer",
    category: "wireless_iot",
    condition: "brand_new",
    pricePkr: 1650,
    originalPricePkr: 2400,
    isNegotiable: false,
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Brand new sealed in anti-static bag. Bought extra for IoT surveillance lab module. Comes with 2MP OV2640 camera lens and FT232RL FTDI USB-to-TTL programmer with jumper wires so you can flash code directly without any extra parts.",
    specs: {
      "Chip": "ESP32-S dual-core 32-bit LX6",
      "Camera": "OV2640 2 Megapixel (Supports JPEG streaming)",
      "Flash": "Built-in bright LED flash light",
      "Wireless": "802.11 b/g/n Wi-Fi + BLE 4.2",
    },
    seller: {
      id: "u-102",
      name: "Ali Raza Khan",
      university: "FAST-NUCES Lahore",
      campus: "Faisal Town Campus",
      city: "Lahore",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 5.0,
      phone: "+923214449876",
    },
    quantityAvailable: 3,
    status: "available",
    createdAt: "2026-08-31T14:30:00Z",
    viewsCount: 92,
    location: "FAST Lahore / Faisal Town / Garden Town",
  },
  {
    id: "tech-003",
    title: "STM32F401CCU6 BlackPill (ARM Cortex-M4 84MHz) + ST-Link V2 Debugger",
    category: "microcontrollers",
    condition: "brand_new",
    pricePkr: 2100,
    originalPricePkr: 3200,
    isNegotiable: true,
    images: [
      "https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Original WeAct BlackPill STM32F401 board with pre-soldered precision pin headers. USB-C interface with DFU bootloader. Bundle includes mini ST-Link V2 programmer for Keil / STM32CubeIDE debugging.",
    specs: {
      "Core": "ARM 32-bit Cortex-M4 with FPU @ 84MHz",
      "Flash / SRAM": "256 KB Flash, 64 KB SRAM",
      "USB": "Type-C connector with OTG support",
      "Debugger": "ST-Link V2 (SWD) with 4-pin cable",
    },
    seller: {
      id: "u-103",
      name: "Zainab Fatima",
      university: "GIKI Topi",
      campus: "Swabi Campus",
      city: "Topi",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 4.8,
      phone: "+923331112233",
    },
    quantityAvailable: 2,
    status: "available",
    createdAt: "2026-08-29T18:00:00Z",
    viewsCount: 210,
    location: "GIKI Campus / Delivery to Rawalpindi & Peshawar",
  },
  {
    id: "tech-004",
    title: "NEMA 17 Stepper Motor (High Torque 42Ncm) + TB6600 4A Stepper Driver",
    category: "motors_actuators",
    condition: "gently_used",
    pricePkr: 2850,
    originalPricePkr: 4500,
    isNegotiable: true,
    images: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Used for 2 weeks on a CNC plotter project. High torque 1.8 degree step angle. Includes high quality optocoupled TB6600 driver (supports microstepping up to 1/32 and 9-42V input). Works smoothly with Arduino CNC shield and GRBL.",
    specs: {
      "Holding Torque": "42 N.cm (60 oz.in)",
      "Current": "1.5A per phase",
      "Driver": "TB6600 (Up to 4A peak, 32 microstep settings)",
      "Shaft": "5mm D-shaft with mounting bracket",
    },
    seller: {
      id: "u-104",
      name: "Usman Ghani",
      university: "UET Taxila",
      campus: "Main Campus Taxila",
      city: "Taxila",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 4.9,
      phone: "+923459998877",
    },
    quantityAvailable: 4,
    status: "available",
    createdAt: "2026-08-31T09:15:00Z",
    viewsCount: 77,
    location: "UET Taxila / Saddar Rawalpindi",
  },
  {
    id: "tech-005",
    title: "3S 2200mAh 11.1V 35C LiPo Battery + IMAX B6 80W Digital Balance Charger",
    category: "power_bms",
    condition: "fyp_tested",
    pricePkr: 4900,
    originalPricePkr: 8200,
    isNegotiable: true,
    images: [
      "https://images.unsplash.com/photo-1608613304899-ea8098577e38?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Used in our Autonomous Drone FYP. Only 8 charge-discharge cycles, zero puffing, internal cell resistance balanced perfectly (~3.85V storage charge currently maintained). Comes with IMAX B6 digital balance charger with 12V 5A power supply.",
    specs: {
      "Capacity": "2200mAh 3S1P (11.1V)",
      "Discharge Rate": "35C Constant, 70C Burst (XT60 connector)",
      "Charger": "IMAX B6 80W Microprocessor Controlled",
      "Safety": "Comes with Fireproof LiPo Safe Guard Bag",
    },
    seller: {
      id: "u-105",
      name: "Bilal Mehmood",
      university: "NED UET Karachi",
      campus: "Main Campus, University Road",
      city: "Karachi",
      avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 5.0,
      phone: "+923002223344",
    },
    quantityAvailable: 1,
    status: "available",
    createdAt: "2026-08-28T16:45:00Z",
    viewsCount: 165,
    location: "NED Karachi / Gulshan-e-Iqbal / Johar",
  },
  {
    id: "tech-006",
    title: "USB Logic Analyzer 24MHz 8-Channel (Saleae Compatible) with Test Hooks",
    category: "test_tools",
    condition: "brand_new",
    pricePkr: 1450,
    originalPricePkr: 2200,
    isNegotiable: false,
    images: [
      "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Essential for hardware & embedded debugging! Decodes I2C, SPI, UART, CAN, 1-Wire protocol in real time. Works with PulseView / Sigrok on Windows, Mac, and Linux. Comes with mini USB cable and 10-pack gripper test clips.",
    specs: {
      "Sampling Rate": "24 MHz Max",
      "Channels": "8 Channels logic capture",
      "Input Voltage": "0V to 5.5V (Supports 3.3V and 5V logic)",
      "Software": "Sigrok / PulseView / Saleae Logic 1.x compatible",
    },
    seller: {
      id: "u-106",
      name: "Saad Sheikh",
      university: "COMSATS Islamabad",
      campus: "Park Road Campus",
      city: "Islamabad",
      avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 4.7,
      phone: "+923129876543",
    },
    quantityAvailable: 5,
    status: "available",
    createdAt: "2026-08-30T22:10:00Z",
    viewsCount: 180,
    location: "COMSATS Islamabad / Chak Shahzad / Tarlai",
  },
  {
    id: "tech-007",
    title: "MPU-6050 6-Axis Gyroscope & Accelerometer Module with I2C Jumper Wires",
    category: "sensors",
    condition: "brand_new",
    pricePkr: 480,
    originalPricePkr: 750,
    isNegotiable: false,
    images: [
      "https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Original GY-521 MPU6050 module with onboard voltage regulator. Perfect for self-balancing robots, flight controllers, and gesture recognition. Pre-soldered straight headers.",
    specs: {
      "Sensors": "3-Axis Gyroscope + 3-Axis Accelerometer + Temp",
      "Interface": "I2C standard communication",
      "Supply Voltage": "3.3V - 5V DC",
      "Resolution": "16-bit ADC conversion per channel",
    },
    seller: {
      id: "u-101",
      name: "Hamza Tariq",
      university: "NUST (SEECS)",
      campus: "Sector H-12, Islamabad",
      city: "Islamabad",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 4.9,
      phone: "+923005551234",
    },
    quantityAvailable: 6,
    status: "available",
    createdAt: "2026-08-31T20:00:00Z",
    viewsCount: 64,
    location: "NUST H-12 Campus",
  },
  {
    id: "tech-008",
    title: "20x4 Character LCD Display (Blue Backlight) with Pre-Soldered I2C Backpack",
    category: "displays",
    condition: "gently_used",
    pricePkr: 1100,
    originalPricePkr: 1650,
    isNegotiable: true,
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Clear 20 character 4 line display with PCF8574 I2C daughterboard attached so you only need 2 pins (SDA/SCL) on your Arduino/ESP32. Contrast potentiometer pre-adjusted.",
    specs: {
      "Display Format": "20 Characters x 4 Lines",
      "Interface": "I2C (Address 0x27 / 0x3F)",
      "Backlight": "Bright Blue with White Characters",
      "Voltage": "5V DC",
    },
    seller: {
      id: "u-104",
      name: "Usman Ghani",
      university: "UET Taxila",
      campus: "Main Campus Taxila",
      city: "Taxila",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      isVerifiedStudent: true,
      rating: 4.9,
      phone: "+923459998877",
    },
    quantityAvailable: 2,
    status: "available",
    createdAt: "2026-08-27T11:20:00Z",
    viewsCount: 52,
    location: "UET Taxila / Wah Cantt",
  },
];

export const MOCK_SERVICES: ServiceRequest[] = [
  {
    id: "srv-001",
    serviceType: "pcb_design",
    title: "4-Layer IoT Gateway PCB Schematic & Layout with Impedance Control",
    description:
      "ESP32-S3 + SIM7600G-H LTE modem baseboard with isolated RS485 and wide input (9-36V) DC-DC buck converter. KiCad 8 source files and Gerber package delivered.",
    clientName: "Daniyal Ahmed",
    clientUniversity: "NUST SEECS",
    clientPhone: "+923001112233",
    files: [{ name: "schematic_draft_v2.pdf", size: "2.4 MB", type: "PDF" }],
    estimatedCostPkr: 8500,
    status: "in_progress",
    createdAt: "2026-08-28T12:00:00Z",
    deadline: "2026-09-10",
  },
  {
    id: "srv-002",
    serviceType: "3d_printing",
    title: "Custom Weather-Proof Drone Gimbal & Flight Controller Enclosure",
    description:
      "Printed in Matte Black PETG at 0.16mm layer height with 40% gyroid infill and brass heat-set M3 threaded inserts.",
    clientName: "Kashif Nisar",
    clientUniversity: "Air University Islamabad",
    clientPhone: "+923451234567",
    files: [{ name: "drone_gimbal_v4.stl", size: "14.8 MB", type: "STL" }],
    estimatedCostPkr: 3200,
    status: "completed",
    createdAt: "2026-08-25T09:00:00Z",
    deadline: "2026-08-30",
  },
];
